config/routes.rb
Rails.application.routes.draw do
  get 'stories/new'

  get 'users/new'

  root 'static_pages#home'

  get  '/help', to: 'static_pages#help'

  get  '/about',   to: 'static_pages#about'

  # get  '/stories', to: 'static_pages#stories'
  
  get  '/signup', to: 'users#new'

  resources :users
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
    validates :PPE_type1, presence: true,
    length: {minimum: 1, maximum: 30}
    validates :Amount1, presence: true,
    length: {minimum: 1, maximum: 30}
    validates :Recipient1, presence: true,
    length: {minimum: 1, maximum: 30}
    validates :PPE_type2, presence: true,
    length: {minimum: 1, maximum: 30}
    validates :Amount2, presence: true,
    length: {minimum: 1, maximum: 30}
    validates :Recipient2, presence: true,
    length: {minimum: 1, maximum: 30}
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def stories
    @story_number = (1..3).to_a.shuffle.first
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params) 
    if @story.save
      redirect_to story_url(@story)
    else
      render 'new'
    end
   end
  
  def show
    @story = Story.find(params[:id])
  end

  private
    def story_params 
      params.require(:story).permit(:PPE_type1, :Amount1, :Recipient1,:PPE_type2, :Amount2, :Recipient2)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      redirect_to user_url(@user)
    else
      render 'new'
    end
   end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
    def user_params 
      params.require(:user).permit(:name, :email, :password,:password_confirmation)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper

    # Returns the full title on a per-page basis.
    def full_title(page_title = '')
      base_title = "Moral sampling for COVID-19"
      if page_title.empty?
        base_title
      else
        page_title + " | " + base_title
      end
    end
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase) 
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}" 
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/XinyaYang0506">Xinya Yang</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "COVID-19", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <li><a href="#">Log in</a></li>
            <li><%= link_to "Sign up", signup_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %> 
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About this website</h1>
<p>
    This website is part of individual project for <a
    href="https://csc324-326.sites.grinnell.edu/">CSC-324</a> written by Xinya
    Yang. This website is built on Ruby on Rails framework. It has a model
    portion where the data in database is defined, a controller portion where
    CRUD methods are defined, a view portion where HTML is embeded in ruby
    files, and other supporting files. Form feature is used to collect user
    input. This website has extensive testing as well. 
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
    More contents to come!
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "") %>
<div class="center jumbotron">
<h1>A moral sampling and model for COVID-19</h1>
<%= image_tag("logo.png", :alt => "logo!") %>
<p>
    In this website you can browse through a variety of dilemma taken place
    during the <a href=https://en.wikipedia.org/wiki/2019-nCoV_acute_respiratory_disease>COVID-19</a> epidemic and make decisions. Your input will be
    recorded as an entry for the whole database to model the HUMAN's choice. 
</p>
  <%= link_to "Story 1", 'stories/1', class: "btn btn-lg
  btn-primary" %>
  <%= link_to "Story 2", 'stories/2', class: "btn btn-lg
  btn-primary" %>
  <%= link_to "Story 3", 'stories/3', class: "btn btn-lg
  btn-primary" %>
  <%= link_to "Create your own", 'stories/new', class: "btn btn-lg
  btn-primary" %>
  
</div>

app/views/static_pages/stories.html.erb
<% provide(:title, "Help") %>
<h1>Stories</h1>
<p>
    STUB for No.<%= @story_number %> story. 
</p>

app/views/stories/new.html.erb
<% provide(:title, 'New Story') %>
   <h1>Creat A New Story</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with model: @story do |form| %> 
            <%= form.label(:PPE_type1, "PPE_type1") %>
            <%= form.text_field(:PPE_type1) %>
            <%= form.label(:Amount1, "Amount1") %>
            <%= form.text_field(:Amount1) %>
            <%= form.label(:Recipient1, "Recipient1") %>
            <%= form.text_field(:Recipient1) %>

            <%= form.label(:PPE_type2, "PPE_type2") %>
            <%= form.text_field(:PPE_type2) %>
            <%= form.label(:Amount2, "Amount2") %>
            <%= form.text_field(:Amount2) %>
            <%= form.label(:Recipient2, "Recipient2") %>
            <%= form.text_field(:Recipient2) %>

            <%= submit_tag("Create this story", class: "btn btn-primary") %>
        <% end %>
    </div>
</div>

app/views/stories/show.html.erb
<% provide(:title, @story.id) %> 
<div class="row">
  <aside class="col-md-4"> 
  <section class="user_info">
  <h1>
    Story <%=@story.id %> 
  </h1>
  <body>
  <table >
    <tr>
    <th> </th>
    <th>Option 1</th>
    <th>Option 2</th>
    </tr>

    <tr>
      <td>PPE_type</td>
      <td><%= @story.PPE_type1 %></td>
      <td><%= @story.PPE_type2 %></td>
    </tr> 

    <tr>
      <td>Amount</td>
      <td><%= @story.Amount1 %></td>
      <td><%= @story.Amount2 %></td>
    </tr> 

    <tr>
      <td>Recipient</td>
      <td><%= @story.Recipient1 %></td>
      <td><%= @story.Recipient2 %></td>
    </tr> 
  </table>
  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
   <h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %> 
            <%= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
                
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control'%>
            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %> <div class="row">
<aside class="col-md-4"> <section class="user_info">
<h1>
<%= gravatar_for @user %>
<%= @user.name %> </h1>
       </section>
     </aside>
</div>